version: '3.8'

services:
  app:
    container_name: app
    hostname: app
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - '.:/app'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=app
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db
    networks:
      - db
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4
    restart: always
    ports:
      - 3307:8080
    environment:
      - ADMINER_DEFAULT=mysql
      - ADMINER_DESIGN=dracula
    depends_on:
      - db
    networks:
      - db
  db:
    container_name: db
    hostname: db
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - 8889:3306
    volumes:
      - './.db:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db
networks:
  db:
    driver: bridge
